### ISSUE TITLE
tvOS Compatibility 

### ISSUE THREAD

**Issue by jeffreyjbrown** [Ethenyl/JAMFKit#78]
### Missing functionnality ###

Hi 👋 ,

Looking to please request `tvos` compatibility to pull in data from our Jamf instance to Apple TV Dashboard. 

Platform syntax in podfile:
```platform :tvos, '10.0'```

`pod install` returns:

```[!] The platform of the target `Dashboard` (tvOS 10.0) is not compatible with `JAMFKit (0.3.0)`, which does not support `tvos` ```

Thank you! :) 

## Miscellaneous ##

Information                   | Value                        |
------------------------------|------------------------------|
Language                      | Swift
Platform                      | tvOS
Platform version              | 10.0
JamfKit version               |  latest as of March 3rd 2018
Package manager               | CocoaPods
Package manager version       | 1.3.1
XCode version                 | 9.2

**Comment by damien-rivet** [comment]
Hi @jeffreyjbrown,

Thanks for pointing that missing compatibility. I've started working on adding the `tvOS` capability, it should be part of the **v0.4.0** release.

**Comment by damien-rivet** [comment]
@jeffreyjbrown the `tvOS` compatibility has been implemented by #79 and will be part of the **v0.4.0** release.

In the meantime, feel free to test by targeting the `develop` branch on `CocoaPods` or `Carthage`, any feedback is welcome as this stage.
